### ISSUE TITLE
learn from each other or even work together: flask-appengine-template & gae-init

### ISSUE THREAD

**Issue by joernhees** [kamalgill/flask-appengine-template#55]
After several projects on appengine and a recurring set of problems i thought about writing a template myself, but before doing that i set out to look at what exists... So i've played around with flask-appengine-template and @lipis gae-init ( http://gae-init.appspot.com/ ).

I'm not sure you're aware of each others' project, but I thought i'd let you know. Each of your templates is very cool on its own already. Still i think that joining forces would maybe create something even cooler. Even should you disagree (which is understandable considering the amount of work you both must've put into each of the projects), i still think it's worth looking at each others template cause some things are solved better here, some things better there. So some of the differences i've found:

gae-init:
- nice (kickass) oauth integration with flask-login
- lessCSS and coffescript support
- deployment support: minification, library zipping
- i18n support in gae-init-babel

flask-appengine-template:
- cool gae-mini-profiler & debug toolbar integration
- uses virtualenv & pip for dependencies (why not for the internal libs as well?)
- some test snippets (even though a bit old maybe)

So give it a try...

Bit off-topic but as gae-init is on mercurial: there's pretty cool hg via git support: http://felipec.wordpress.com/2012/11/13/git-remote-hg-bzr-2/

PS: also posting this on gae-init as an issue: https://bitbucket.org/lipis/gae-init/issue/6

**Comment by lipis** [comment]
Hi @kamalgill.. it looks like this is a bit outdated at the moment and not maintained.. due to it's popularity though, people are still passing by and just moving on, since there is no much activity. 

What do you say about having a note on top in the [README](https://github.com/kamalgill/flask-appengine-template/blob/master/README.md) about mentioning the fact that this is not maintained and suggesting an active alternative one which is also using Flask and always up to date with the latest GAE (and sometimes trends).. https://github.com/gae-init/gae-init

**Comment by kamalgill** [comment]
@lipis: Agreed, feel free to open a PR for the reame update

**Comment by lipis** [comment]
Thanks man! Much appreciated.. :dancers:
